name: CD

on:
  push:
    branches: [main]
    paths:
      - "tile-creator/**"

concurrency:
  group: cd

jobs:
  publish-tile:
    name: Publish tile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # tag v5.0.0

      - name: Publish tile
        env:
          TESSL_TOKEN: ${{ secrets.TESSL_TOKEN }}
        run: npx @tessl/cli tile publish tile-creator

permissions:
  contents: read
